---
title: "Unit 2: Basketball"
author: "Matt Farrow"
date: "8/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(hrbrthemes)
library(plotly)
```

```{r include=FALSE}
df <- read_csv(here::here("6306", "week 02", "PlayersBBall.csv"), 
               col_types = cols(birth_date = col_date(format = "%B %d, %Y")))
```

## Data Wrangling

```{r}
# Examine the data
glimpse(df)

# Split up positions
df <- df %>% 
  mutate(pos_f = str_detect(df$position, "F"),
         pos_g = str_detect(df$position, "G"),
         pos_c = str_detect(df$position, "C"))

# Convert height
df <- df %>% 
  separate(height, c('feet', 'inches'), "-", convert = TRUE) %>% 
  mutate(cm = (12*feet + inches)*2.54)

# Examine the cleaned data
glimpse(df)
```

## FLS Questions

```{r}
df %>% 
  select(pos_f,
         pos_g,
         pos_c) %>% 
  pivot_longer(cols = c("pos_f", "pos_g", "pos_c"),
               names_to = "position", 
               values_to = "plays") %>% 
  group_by(position) %>% 
  count(plays) %>% 
  filter(plays == TRUE) %>% 
  ungroup() %>% 
  ggplot(aes(position, n)) +
  geom_col(fill = "steelblue") +
  scale_x_discrete(labels = c("Center", "Forward", "Guard")) +
  labs(title = "How are players distributed by position?",
       x = "Position",
       y = "Players",
       caption = "some players may play multiple positions\nsource: NBA basketball players from 1950-2018") +
  theme_ipsum()
```


```{r}
df %>% 
  filter(pos_c != TRUE) %>% 
  pivot_longer(cols = c("pos_f", "pos_g"),
               names_to = "where", 
               values_to = "plays") %>% 
  filter(plays == TRUE) %>% 
  ggplot(aes(where, weight)) +
  geom_boxplot() +
  scale_x_discrete(labels = c("Forward", "Guard")) +
  labs(title = "Is the distribution of the weight of Centers greater than\nForwards?",
       x = "Position",
       y = "Weight (lbs)",
       caption = "some players may play multiple positions\nsource: NBA basketball players from 1950-2018") +
  theme_ipsum()
```

```{r}
df %>% 
  filter(pos_g != TRUE) %>% 
  pivot_longer(cols = c("pos_f", "pos_c"),
               names_to = "where", 
               values_to = "plays") %>% 
  filter(plays == TRUE) %>% 
  ggplot(aes(cm, fill = where)) +
  geom_histogram(ins = 15, position = "dodge", alpha = 0.5) +
  labs(title = "Is the distribution of the height of Centers greater than\nForwards?",
       x = "Position",
       y = "Height (cm)",
       fill = "Position",
       caption = "some players may play multiple positions\nsource: NBA basketball players from 1950-2018") +
  scale_fill_discrete(labels = c("Center", "Forward")) +
  theme_ipsum()
```

```{r}
df %>% 
  pivot_longer(cols = c("pos_f", "pos_g", "pos_c"),
               names_to = "where", 
               values_to = "plays") %>% 
  filter(plays == TRUE) %>% 
  ggplot(aes(where, cm)) +
  geom_boxplot() +
  scale_x_discrete(labels = c("Forward", "Guard", "Center")) +
  labs(title = "Is the distribution of heights different between\nany of the positions?",
       x = "Position",
       y = "Mean Height (cm)",
       caption = "some players may play multiple positions\nsource: NBA basketball players from 1950-2018") +
  theme_ipsum()
```

```{r}
df %>% 
  pivot_longer(cols = c("pos_f", "pos_g", "pos_c"),
               names_to = "where", 
               values_to = "plays") %>% 
  filter(plays == TRUE) %>% 
  ggplot(aes(cm, weight, color = where)) +
  geom_jitter(alpha = 0.3) +
  labs(title = "How is a player's height related to weight?",
       subtitle = "And is there any difference in the relationship between positions?",
       x = "Height (cm)",
       y = "Weight (lbs)",
       color = "Position",
       caption = "some players may play multiple positions\nsource: NBA basketball players from 1950-2018") +
  scale_color_discrete(labels = c("Center", "Forward", "Guard")) +
  theme_ipsum()
```

```{r}
df %>% 
  group_by(year_start) %>% 
  summarise(mean_height = mean(cm)) %>% 
  ungroup() %>% 
  ggplot(aes(year_start, mean_height)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "How have player's heights changed over the years?",
       x = "Start Year",
       y = "Mean Height (cm)",
       caption = "some players may play multiple positions\nsource: NBA basketball players from 1950-2018") +
  theme_ipsum()
```

```{r}
df %>% 
  pivot_longer(cols = c("pos_f", "pos_g", "pos_c"),
               names_to = "where", 
               values_to = "plays") %>% 
  filter(plays == TRUE) %>% 
  plot_ly(x = ~cm, y = ~weight, z = ~year_start, color = ~where) %>% 
  add_markers() %>% 
  layout(scene = list(xaxis = list(title = "Height (cm)"),
                      yaxis = list(title = "Weight (lbs)"),
                      zaxis = list(title = "Start Year")))
```

